name: Run my script

on:
  schedule:
    - cron: '0 0 * * 1'  # Ejecuta cada lunes a las 00:00 UTC
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

# Otorga permisos de escritura al token
permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Usa GITHUB_TOKEN para autenticar

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Ajusta a la versión que necesites

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Instala dependencias si hay un requirements.txt

      - name: Run script
        run: python main.py  # Cambia 'main.py' por tu script principal
        env:
          VALOR_A: ${{ secrets.VALOR_A }}
          VALOR_B: ${{ secrets.VALOR_B }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated commit by GitHub Actions" || echo "No changes to commit"

      - name: Push changes
        run: git push
